### ISSUE TITLE
ConcurrentmodificationException

### ISSUE THREAD

**Issue by m5rian** [CraftTogether/AfkPlugin#1]
[15:15:21 WARN]: Exception in thread "Timer-0" java.util.ConcurrentModificationException
[15:15:21 WARN]:        at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1597)
[15:15:21 WARN]:        at java.base/java.util.HashMap$EntryIterator.next(HashMap.java:1630)
[15:15:21 WARN]:        at java.base/java.util.HashMap$EntryIterator.next(HashMap.java:1628)
[15:15:21 WARN]:        at weg-1.0.jar//xyz.crafttogether.weg.Weg$1.run(Weg.java:53)
[15:15:21 WARN]:        at java.base/java.util.TimerThread.mainLoop(Timer.java:566)
[15:15:21 WARN]:        at java.base/java.util.TimerThread.run(Timer.java:516)

**Comment by ghost** [comment]
@M5rian ah dammit I forgot about synchronization

**Comment by m5rian** [comment]
yeah... I already asked xeri to fix it. Seems like hes already working on it

**Comment by ghost** [comment]
@M5rian I could not reproduce this error, was it fixed?

**Comment by m5rian** [comment]
Not sure. Haven't worked on it.
@x3rition Any updates?
